## C.1 Dimensions

## C.2 The ndarray Object

In [1]:
import numpy as np

### C.2.1. Generating a Numeric Range with the arange Method

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [6]:
tens = np.arange(start = 0, stop = 111, step = 10)

In [7]:
np.arange(start = 2, stop = 6)[::-1]

array([5, 4, 3, 2])

### C.2.2 Attributes on a ndarray Object

In [8]:
tens.shape

(12,)

In [9]:
tens.ndim

1

In [10]:
tens.size

12

### C.2.3 The reshape Method

In [11]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [12]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [13]:
tens.reshape(4, 3).ndim

2

In [14]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [15]:
# tens.reshape(2, 5)

In [16]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [17]:
tens.reshape(2, 3, 2).ndim

3

In [18]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [19]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

### C.2.4 The randint Function

In [32]:
np.random.randint(5)

0

In [21]:
np.random.randint(1, 10)

5

In [22]:
np.random.randint(1, 10, 3)

array([8, 7, 7])

In [23]:
np.random.randint(1, 10, [3])

array([8, 7, 4])

In [24]:
np.random.randint(1, 10, [3, 5])

array([[5, 9, 8, 7, 5],
       [4, 2, 1, 5, 4],
       [2, 2, 7, 6, 3]])

### C.2.5 The randn Function

In [25]:
# 1x3 one-dimensional array
np.random.randn(3)

array([-0.18060422, -0.28834734,  0.46073738])

In [26]:
# 2x4 two-dimensional array
np.random.randn(2, 4)

array([[ 1.84508752,  0.76603376, -0.40948617, -1.04705246],
       [ 3.09118939,  0.81105086, -0.7893233 ,  1.50102168]])

In [27]:
# 2x4x3 three-dimensional array
np.random.randn(2, 4, 3)

array([[[ 1.19318278e+00,  8.04981116e-01,  4.91893358e-02],
        [-1.36530833e+00,  5.51071462e-01, -4.92645544e-01],
        [-1.21337409e+00, -4.68553104e-01, -3.48229380e-01],
        [ 4.07785506e-04, -2.18247057e-01, -1.90459174e+00]],

       [[ 9.21194453e-01, -4.95373032e-01,  6.22441805e-02],
        [-1.56115627e+00,  2.46989485e-01, -4.48396383e-01],
        [-6.48095876e-01,  1.66021452e+00,  1.74430827e-01],
        [ 1.08662459e+00,  5.83805463e-01,  3.64990154e-01]]])

## C.3 The nan Object

In [28]:
np.nan

nan

In [29]:
np.nan == np.nan

False

## C.4 Summary