## C.1 Dimensions

## C.2 The ndarray Object

In [1]:
import numpy as np

### C.2.1. Generating a Numeric Range with the arange Method

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 2, stop = 6)[::-1]

array([5, 4, 3, 2])

In [6]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [7]:
tens = np.arange(start = 0, stop = 111, step = 10)

### C.2.2 Attributes on a ndarray Object

In [8]:
tens.shape

(12,)

In [9]:
tens.ndim

1

In [10]:
tens.size

12

### C.2.3 The reshape Method

In [11]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [12]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [13]:
tens.reshape(4, 3).ndim

2

In [14]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [15]:
# tens.reshape(2, 5)

In [16]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [17]:
tens.reshape(2, 3, 2).ndim

3

In [18]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [19]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

### C.2.4 The randint Function

In [20]:
np.random.randint(5)

3

In [21]:
np.random.randint(1, 10)

1

In [22]:
np.random.randint(1, 10, 3)

array([2, 5, 8])

In [23]:
np.random.randint(1, 10, [3])

array([2, 6, 1])

In [24]:
np.random.randint(1, 10, [3, 5])

array([[6, 1, 3, 8, 5],
       [4, 4, 5, 9, 4],
       [6, 4, 7, 9, 5]])

### C.2.5 The randn Function

In [25]:
# 1x3 one-dimensional array
np.random.randn(3)

array([ 0.3436771 , -1.19182747,  0.77547342])

In [26]:
# 2x4 two-dimensional array
np.random.randn(2, 4)

array([[-1.42022037, -0.03675303,  0.09556172,  0.35292078],
       [-0.40262741, -0.63251327,  0.66813494, -0.92139341]])

In [27]:
# 2x4x3 three-dimensional array
np.random.randn(2, 4, 3)

array([[[ 0.05418791,  1.4057464 , -1.64490362],
        [-1.57616502,  1.34474377,  1.13392493],
        [ 0.95394833,  0.6210138 , -1.88955779],
        [-0.33900822,  0.90649632,  0.05468176]],

       [[ 1.5272448 ,  1.12475249, -1.94177389],
        [ 1.04152698,  0.09925981,  0.48643009],
        [-0.43005471, -1.85119005, -0.61664444],
        [ 1.05535561,  0.75482542, -0.45070499]]])

## C.3 The nan Object

In [28]:
np.nan

nan

In [29]:
np.nan == 5

False

In [30]:
np.nan == np.nan

False

## C.4 Summary