## C.1 Dimensions

## C.2 The ndarray Object

In [1]:
import numpy as np

### C.2.1. Generating a Numeric Range with the arange Method

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [6]:
tens = np.arange(start = 0, stop = 111, step = 10)

In [7]:
np.arange(start = 2, stop = 6)[::-1]

array([5, 4, 3, 2])

### C.2.2 Attributes on a ndarray Object

In [8]:
tens.shape

(12,)

In [9]:
tens.ndim

1

In [10]:
tens.size

12

### C.2.3 The reshape Method

In [11]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [12]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [13]:
tens.reshape(4, 3).ndim

2

In [14]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [15]:
# tens.reshape(2, 5)

In [16]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [17]:
tens.reshape(2, 3, 2).ndim

3

In [18]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [19]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

### C.2.4 The randint Function

In [20]:
np.random.randint(5)

0

In [21]:
np.random.randint(1, 10)

8

In [22]:
np.random.randint(1, 10, 3)

array([7, 8, 5])

In [23]:
np.random.randint(1, 10, [3])

array([1, 4, 2])

In [24]:
np.random.randint(1, 10, [3, 5])

array([[8, 3, 3, 1, 2],
       [3, 9, 2, 1, 8],
       [1, 5, 9, 8, 4]])

### C.2.5 The randn Function

In [25]:
# 1x3 one-dimensional array
np.random.randn(3)

array([-0.51445105,  0.44529902,  0.55134909])

In [26]:
# 2x4 two-dimensional array
np.random.randn(2, 4)

array([[ 0.08761305,  0.48903499, -1.11100888, -0.77128994],
       [-0.11951192,  0.06912946, -0.65190799, -0.66226326]])

In [27]:
# 2x4x3 three-dimensional array
np.random.randn(2, 4, 3)

array([[[ 1.41948288, -1.1789568 , -0.5542374 ],
        [ 1.04931284,  1.03035735, -1.18926816],
        [ 0.09658683, -0.43617696, -0.0533664 ],
        [ 0.59038881,  1.04970008, -1.14893112]],

       [[-0.84752391, -0.11628415,  0.79855112],
        [ 0.93716275,  0.5228684 ,  1.9662257 ],
        [ 0.7754832 , -0.868223  , -0.36061323],
        [ 0.72316842,  1.7166146 ,  1.06688111]]])

## C.3 The nan Object

In [28]:
np.nan

nan

In [29]:
np.nan == np.nan

False

## C.4 Summary