## C.1 Dimensions

## C.2 The ndarray Object

In [1]:
import numpy as np

### C.2.1. Generating a Numeric Range with the arange Method

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [6]:
tens = np.arange(start = 0, stop = 111, step = 10)

### C.2.2 Attributes on a ndarray Object

In [7]:
tens.shape

(12,)

In [8]:
tens.ndim

1

In [9]:
tens.size

12

### C.2.3 The reshape Method

In [10]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [11]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [12]:
tens.reshape(4, 3).ndim

2

In [13]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [14]:
# tens.reshape(2, 5)

In [15]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [16]:
tens.reshape(2, 3, 2).ndim

3

In [17]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [18]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

### C.2.4 The randint Function

In [19]:
np.random.randint(5)

0

In [20]:
np.random.randint(1, 10)

2

In [21]:
np.random.randint(1, 10, 3)

array([9, 8, 7])

In [22]:
np.random.randint(1, 10, [3])

array([3, 8, 5])

In [23]:
np.random.randint(1, 10, [3, 5])

array([[4, 9, 1, 9, 1],
       [7, 7, 5, 1, 3],
       [6, 3, 5, 2, 9]])

### C.2.5 The randn Function

In [24]:
np.random.randn(3)

array([0.11203548, 0.63477879, 1.36429377])

In [25]:
np.random.randn(2, 4)

array([[-2.57520867,  0.76308781,  1.02989935,  0.22036127],
       [ 0.27405633,  0.48367557,  0.26292838,  0.22931682]])

In [26]:
np.random.randn(2, 4, 3)

array([[[ 0.24688511,  1.901612  ,  0.21666655],
        [ 0.71110634, -2.36315733,  0.71948913],
        [ 0.49006531,  0.05976746,  0.37220836],
        [-1.09461527, -0.54652626,  1.62655736]],

       [[ 1.11408718,  1.81681574,  1.30602374],
        [-2.21348346,  1.46361558,  0.3624754 ],
        [ 0.65080062, -0.67317425,  0.73057612],
        [ 0.18857014,  2.11698987,  0.40056288]]])

## C.3 The nan Object

In [27]:
np.nan

nan

In [28]:
np.nan == 5

False

In [29]:
np.nan == np.nan

False

## C.4 Summary