## C.1 Dimensions

## C.2 The ndarray Object

In [1]:
import numpy as np

### C.2.1. Generating a Numeric Range with the arange Method

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [6]:
tens = np.arange(start = 0, stop = 111, step = 10)

### C.2.2 Attributes on a ndarray Object

In [7]:
tens.shape

(12,)

In [8]:
tens.ndim

1

In [9]:
tens.size

12

### C.2.3 The reshape Method

In [10]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [11]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [12]:
tens.reshape(4, 3).ndim

2

In [13]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [14]:
# tens.reshape(2, 5)

In [15]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [16]:
tens.reshape(2, 3, 2).ndim

3

In [17]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [18]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

### C.2.4 The randint Function

In [19]:
np.random.randint(5)

4

In [20]:
np.random.randint(1, 10)

9

In [21]:
np.random.randint(1, 10, 3)

array([6, 9, 3])

In [22]:
np.random.randint(1, 10, [3])

array([9, 5, 6])

In [23]:
np.random.randint(1, 10, [3, 5])

array([[7, 7, 5, 8, 6],
       [9, 6, 2, 8, 8],
       [1, 4, 7, 1, 4]])

### C.2.5 The randn Function

In [24]:
np.random.randn(3)

array([ 1.73019541, -0.61576962,  0.40545424])

In [25]:
np.random.randn(2, 4)

array([[-0.0756701 , -0.44763163,  1.36888187, -1.67666957],
       [-1.18730507, -1.15721547,  0.24441294, -0.07029716]])

In [26]:
np.random.randn(2, 4, 3)

array([[[-0.43053396,  0.32434483,  0.44760456],
        [-2.23207692, -0.64579377, -0.41323321],
        [-0.4873963 , -0.26698952, -1.31456687],
        [-0.24223568, -1.38016695, -0.71684854]],

       [[ 1.39104561, -0.89610093,  0.36187876],
        [ 0.52248473, -1.00531149,  0.07652011],
        [-0.21747375, -0.52856332, -0.17073731],
        [ 0.23561638, -0.27641097,  0.56215813]]])

## C.3 The nan Object

In [27]:
np.nan

nan

In [28]:
np.nan == 5

False

In [29]:
np.nan == np.nan

False

## C.4 Summary