## C.1 Dimensions

## C.2 The ndarray Object

In [1]:
import numpy as np

### C.2.1. Generating a Numeric Range with the arange Method

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 2, stop = 6)[::-1]

array([5, 4, 3, 2])

In [6]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [7]:
tens = np.arange(start = 0, stop = 111, step = 10)

### C.2.2 Attributes on a ndarray Object

In [8]:
tens.shape

(12,)

In [9]:
tens.ndim

1

In [10]:
tens.size

12

### C.2.3 The reshape Method

In [11]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [12]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [13]:
tens.reshape(4, 3).ndim

2

In [14]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [15]:
# tens.reshape(2, 5)

In [16]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [17]:
tens.reshape(2, 3, 2).ndim

3

In [18]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [19]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

### C.2.4 The randint Function

In [20]:
np.random.randint(5)

4

In [21]:
np.random.randint(1, 10)

7

In [22]:
np.random.randint(1, 10, 3)

array([3, 5, 5])

In [23]:
np.random.randint(1, 10, [3])

array([1, 2, 2])

In [24]:
np.random.randint(1, 10, [3, 5])

array([[2, 6, 4, 1, 3],
       [9, 6, 7, 4, 3],
       [3, 9, 7, 4, 1]])

### C.2.5 The randn Function

In [25]:
np.random.randn(3)

array([ 0.75052557,  0.41543057, -1.16577028])

In [26]:
np.random.randn(2, 4)

array([[ 1.21273968,  0.17777818, -2.40995869, -0.79211619],
       [-1.21395628,  0.2404374 , -1.09720478,  0.63984212]])

In [27]:
np.random.randn(2, 4, 3)

array([[[ 1.81586204,  0.48469845,  1.3008591 ],
        [ 0.80807732, -0.32370531, -0.97297362],
        [-0.71356671,  0.3857115 , -0.30321874],
        [ 1.79625597, -0.45456587,  0.42699196]],

       [[-0.16446697, -0.86319189,  0.54424092],
        [ 1.26237927, -1.53678464,  0.11590464],
        [-1.09459215, -1.0237781 ,  0.55101829],
        [-1.05316985, -2.44946081, -1.83136811]]])

## C.3 The nan Object

In [28]:
np.nan

nan

In [29]:
np.nan == 5

False

In [30]:
np.nan == np.nan

False

## C.4 Summary