## 4.1 Dimensions

## 4.2 The ndarray Object

In [1]:
import numpy as np

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 2, stop = 6)[::-1]

array([5, 4, 3, 2])

In [6]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [7]:
tens = np.arange(start = 0, stop = 111, step = 10)

In [8]:
tens.shape

(12,)

In [9]:
tens.ndim

1

In [10]:
tens.size

12

In [11]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [12]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [13]:
tens.reshape(4, 3).ndim

2

In [14]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [15]:
# tens.reshape(2, 5)

In [16]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [17]:
tens.reshape(2, 3, 2).ndim

3

In [18]:
np.random.randint(5)

0

In [19]:
np.random.randint(1, 10)

8

In [20]:
np.random.randint(1, 10, 3)

array([7, 2, 8])

In [21]:
np.random.randint(1, 10, [3])

array([3, 9, 8])

In [22]:
np.random.randint(1, 10, [3, 5])

array([[4, 5, 3, 8, 3],
       [9, 7, 3, 3, 7],
       [5, 5, 6, 7, 7]])

In [23]:
np.random.randn(3)

array([1.15070996, 0.89150832, 0.06655173])

In [24]:
np.random.randn(2, 4)

array([[0.75066397, 2.05911303, 0.28537386, 1.45475954],
       [0.17388233, 0.4763061 , 0.23846216, 1.00952657]])

In [25]:
np.random.randn(2, 4, 3)

array([[[ 1.88884808, -0.61736603,  0.39125986],
        [-1.93835598,  0.57526912, -0.88325583],
        [-0.14678769, -0.94685908, -0.11393502],
        [ 1.47268955, -0.25792278,  0.03768654]],

       [[-2.35926277, -0.37139096,  1.62017796],
        [-0.59082128,  0.14827057,  1.31358283],
        [ 0.76028342, -0.90109283, -0.83706776],
        [-0.64473189, -0.10027287,  1.74136137]]])

## 4.3 The nan Object

In [26]:
np.nan

nan

In [27]:
np.nan == np.nan

False